version: "3"
services:
    tensorflow-serving:
        build:
            context: ./services/tensorflow-serving
            dockerfile: Dockerfile.tf
        container_name: tensorflow-serving
        ports:
            - "8501:8501"
        depends_on:
            - flask

    flask:
        build:
            context: ./services/flask
            dockerfile: Dockerfile.flask
        container_name: flask
    nginx:
        build:
            context: ./services/nginx
            dockerfile: Dockerfile.nginx
        container_name: nginx
        ports:
            - "1337:443"
