version: "3"
services:
    tensorflow-serving:
        build:
            context: ./services/tensorflow-serving
            dockerfile: Dockerfile.tf
        command:
            - "--model_config_file=/models/model.config"
        container_name: tensorflow-serving
        ports:
            - "8501:8501"
        depends_on:
            - flask

    nginx:
        build:
            context: ./services/nginx
            dockerfile: Dockerfile.nginx
        container_name: nginx
        ports:
            - "80:80"
        depends_on:
            - flask

    flask:
        build:
            context: ./services/flask
            dockerfile: Dockerfile.flask
        container_name: flask
        environment:
            TENSORFLOW_SERVING_HOST: "tensorflow-serving"
