FROM python:3.10-slim-buster

# Copy source code
COPY . /services/flask

# Upgrade pip
RUN pip install --upgrade pip

# Install the requirements
COPY requirements.txt /services/flask/requirements.txt
RUN pip install -r /services/flask/requirements.txt

# Add to PYTHONPATH so can see necessary Python modules in Docker when using absolute imports
ENV PYTHONPATH "${PYTHONPATH}:/services/flask"

# Start gunicorn
CMD ["gunicorn", "-c", "/services/flask/gunicorn_config.py", "--preload", "wsgi:app"]
