FROM python:3.10-slim-buster

# Copy source code and set working directory
COPY . /app
WORKDIR /app

# Upgrade pip
RUN pip install --upgrade pip

# Install the requirements
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Start gunicorn
CMD ["gunicorn", "wsgi:app", "--workers=2", "--threads=2", "--bind=0.0.0.0:8000"]
