# This workflow will run tests

name: Test application

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t traffic .
      - name: Run container
        run: docker run --rm -d --name traffic -e TF_CPP_MIN_LOG_LEVEL="3" -v "$(pwd)/tests:/tests" -v "$(pwd)/model:/model" -v "$(pwd)/static:/static" traffic > /dev/null  # redirect output excluding errors
      - name: Run tests
        run: docker exec traffic  python -m pytest tests/
