# This workflow will run tests

name: Test application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker-compose up -d --build
      - name: List container
        run: docker-compose ps
      - name: Run tests
        run: docker-compose run --rm -e TF_CPP_MIN_LOG_LEVEL="3" -v "$(pwd)/tests:/tests" -v "$(pwd)/services:/services" flask python3 -m unittest discover -s /tests -p "test*"
