# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Install Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - name: remote-bash
        uses: shinhwagk/remote-bash@0.0.1
        env:
          REMOTE_BASH_URL: https://raw.githubusercontent.com/DanielTsiang/traffic-sign-classifier/main/tests/test.sh
